require "coveralls"
Coveralls.wear!

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.before(:all) do
    @hash = {
      name: "Peter",
      address: { wrong: '#$$$$$', correct: :'10-30:L_' },
      city: { wrong: "Germany", correct: :'Madrid|Barcelona|London|Akureyri' },
      products: [
        {
          name: :'10:Ln',
          price: { wrong: "-20", correct: :'1-10:N' },
        },
        {
          name: :'10:Ln',
          price: { wrong: "-30", correct: :'1-10:N' },
        },
      ],
    }
    @hashc = {
      name: "Peter",
      address: :'10-30:L_',
      city: :'Madrid|Barcelona|London|Akureyri',
      products: [
        {
          name: :'10:Ln',
          price: :'1-10:N',
        },
        {
          name: :'10:Ln',
          price: :'1-10:N',
        },
      ],
    }
    @hashw = {
      name: "Peter",
      address: '#$$$$$',
      city: "Germany",
      products: [
        {
          name: :'10:Ln',
          price: "-20",
        },
        {
          name: :'10:Ln',
          price: "-30",
        },
      ],
    }
    @hashopt = {
      customer: Boolean,
      created: DateTime,
      name: :'10-20:L_',
      [:pwd1, :pwd2, :pwd3] => :"5-10:L/n/",
      age: 18..120,
      euros: -3000.0..3000.0,
      #wallet: 0..    #infinite only working Ruby >=2.6
      reports: :"Weekely|Daily",
      username: /[a-z]{10,20}/,
    }

    @my_hash = {
      loginame: :"5-10:/xn/",
      [:pwd1, :pwd2, :pwd3] => :"5-10:L/n/",
      name: :"10-20:T_/x/",
      age: 18..120,
      euros: 0.0..3000.0,
      created: DateTime,
      customer: Boolean,
      draws: [
        {
          drawId: :"5:N",
          drawName: :"10:Ln",
          type: :"Weekely|Daily",
          owner: {
            default: "admin",
            correct: :"20:L",
          },
        },
        {
          drawId: :"5:N",
          drawName: :"10:Ln",
          type: :"Weekely|Daily",
          owner: {
            default: "admin",
            correct: :"20:L",
          },
        },
      ],
      zip: { default: "00000", correct: :'5:N' },
      address: "21 Doom Av",
      city: {
        default: "Madrid",
        correct: "London|Rome",
      },
      wagers: ["34AAB", "dfffDD", "33499A"],
      country: { default: "Spain", correct: ["Spain", "Iceland", "Serbia", "Denmark", "Canada", "Italy", "Austria"].join("|") }, #one of these values
      mobilePhone: { default: "(987)654321", correct: ["(", :'3:N', ")", :'6-8:N'] },
      sex: :"male|female|other", #any of these values
      display: true,
    }
  end

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # This setting enables warnings. It's recommended, but in some cases may
  # be too noisy due to issues in dependencies.
  config.warnings = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
